[webservers]
web-1 ansible_host = 158.160.61.175 fqdn = fhms5563tojnjsha8um3.auto.internal
web-2 ansible_host = 130.193.36.200 fqdn = fhmopka2lej6oq0488eq.auto.internal

[databases]
main ansible_host =  fqdn = fhmj2836blbcv9qsp5n6.auto.internal
replica ansible_host =  fqdn = fhmgrha9mk9u6eb9nf1c.auto.internal

[storage]
storage ansible_host = 111.88.242.249 fqdn = fhm2m5sue7qse5r1qt00.auto.internal
